djan/prop/list/urls.py
from django.urls import path
from . import views
app_name = 'list'

urlpatterns = [
    path('', views.post, name='post'),
    path('new-post/', views.posts_new, name='new-post'),
    path('<slug:slug>', views.post_list, name='post_list'),
]

djan/prop/prop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('list/', include('list.urls')),
    path('',include('users.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djan/prop/users/urls.py
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

djan/prop/list/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class List(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return self.title

djan/prop/list/forms.py
from django import forms
from .models import List

class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['title','body','slug','banner']

djan/prop/list/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import List
from .forms import ListForm

# Create your views here.
def post(request):
    lists = List.objects.all().order_by('-date')
    return render(request, 'list/list.html', {'lists':lists})


def post_list(request, slug):
    post = List.objects.get(slug=slug)
    return render(request, 'list/post_list.html', {'post':post})


@login_required(login_url ='users:login')
def posts_new(request):
    if request.method == 'POST':
        form = ListForm(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save()
            newpost.author = request.user
            newpost.save()
            return redirect('list:new-post')
    else:
        form = ListForm()
    return render(request, 'list/post_new.html', {'form':form})

djan/prop/prop/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    #return HttpResponse("<h1>Hello World<h1>")
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

djan/prop/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('list:post')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('list:post')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('list:post')

djan/prop/list/templates/list/list.html
{% extends 'layout.html' %}
{% block title %}List{% endblock %}
{% block content %}
    <h2>Lists</h2>
    <article>
        {% for list in lists %}
        <a href="{% url 'list:post_list' list.slug %}"><p>{{ list.title }}</p></a>
        <p>{{ list.date }}</p>
        <p>{{ list.body }}</p>
        {% endfor %}
    </article>
    <a href="{% url 'home' %}">Back to Home</a>
{% endblock %}

djan/prop/list/templates/list/post_list.html
{% extends 'layout.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <article>
        <h1>{{ post.title }}</h1>
        <img src="{{ post.banner.url }}" alt="banner" class="banner" width='500' />
        <p>{{ post.slug }}</p>
        <p>{{ post.date }} by {{ post.author }}</p>
        <p>{{ post.body }}</p>
    </article>
    <a href="{% url 'home' %}">Back to Home</a>
{% endblock %}

djan/prop/list/templates/list/post_new.html
{% extends 'layout.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <section>
        <h1>New Post</h1>
        <form action="{% url 'list:new-post' %}" method="post">
            {% csrf_token %}
            {% comment %} {{ form.as_p }} {% endcomment %}
            <table>
                {% for i in form %}
                <tr>
                    <td>{{ i.label_tag }}</td>
                    <td>{{ i }}</td>
                </tr>
                {% endfor %}
            </table>
            <button type="submit" class="form-submit">Submit</button>
        </form>
        <a href="{% url 'home' %}">Back to Home</a>
    </section>
{% endblock %}

djan/prop/templates/about.html
{% extends 'layout.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <h1>My World!</h1>
    <h2>Welcome About</h2>
    <a href="{% url 'home' %}">Back to Home</a>
{% endblock %}

djan/prop/templates/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>Hello World !!!</h1>
    <h2>Welcome Home</h2>
    <a href="{% url 'about' %}">About</a>
{% endblock %}

djan/prop/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">Home</a> | 
        <a href="{% url 'about' %}">About</a> | 
        <a href="{% url 'list:post' %}">List</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'list:new-post' %}">New</a> |
            <form action="{% url 'users:logout' %}" class="logout" method="post">
                {% csrf_token %}
                <button class="logout-button">Logout</button>
            </form> |
        {% else %}
            <a href="{% url 'users:register' %}">Register</a> |
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

djan/prop/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <section style="padding: 10px">
        <h1>Login Form</h1>
        <form action="{% url 'users:login' %}" class='form-with-validation' method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% endif %}
            <button class='form-submit'>Submit</button>
        </form>
    </section>
{% endblock %}

djan/prop/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <section style="padding: 10px">
        <h1>Register Form</h1>
        <form action="{% url 'users:register' %}" class='form-with-validation' method='post'>
            {% csrf_token %}
            {{ form }}
            <button class='form-submit'>Submit</button>
        </form>
    </section>
{% endblock %}